#!/usr/bin/env bash

# One line command, markup_escape is for example for &
# Write stderr to /dev/null. If empty, echo nothing (|| echo "")
playerctl metadata --player=spotify --format '{{ markup_escape(title) }} - {{ markup_escape(artist)}}' 2>/dev/null || echo ""

